# Generated by Django 4.1.7 on 2023-02-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languageApi', '0002_language_word_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(default='korean'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='languageApi.language')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='languageApi.collection'),
        ),
    ]
