# Generated by Django 4.1.5 on 2023-01-31 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('python', models.BooleanField(default=False)),
                ('r_language', models.BooleanField(default=False)),
                ('excel', models.BooleanField(default=False)),
                ('machine_learning', models.BooleanField(default=False)),
                ('hourly_contract', models.BooleanField(default=True)),
                ('django', models.BooleanField(default=False)),
                ('react', models.BooleanField(default=False)),
                ('project_name', models.CharField(default='blank', max_length=20)),
                ('description', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_list', to='webServices.workorder')),
            ],
        ),
    ]
